name: Main
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  schedule:
  - cron: '0 0 * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TurnipGuy30
          repo: Lhn
          template: repository
